### ISSUE TITLE
Unresolved External Symbol

### ISSUE THREAD

**Issue by Komak57** [MeineZ/BMSessionPlugin#1]
Getting a large collection of errors like Unresolved external symbol "__declspec(dllimport) public: __..." when attempting to compile this project. All source appears to be bug-free, compiling Releast/x86, Bakkesmod SDK added as includes from both the GitHub installed version, and the BakkesMod installed version. I'm assuming this has something to do with the compiler settings, but I can't find a solution as to why.

Visual Studio 2017 v15.9.22
Visual Studio 2019 v16.5.4

This code was compiled as both the start of my own plugin, and as the original source from the original solution in the github. The errors following are from the plugin BMDiscord, which are identical to the source compile errors except for file names.

Severity	Code	Description	Project	File	Line	Suppression State

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall CanvasWrapper::~CanvasWrapper(void)" (__imp_??1CanvasWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall CanvasWrapper::CanvasWrapper(class CanvasWrapper const &)" (__imp_??0CanvasWrapper@@QAE@ABV0@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CVarManagerWrapper::log(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (__imp_?log@CVarManagerWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class CVarWrapper __thiscall CVarManagerWrapper::registerCvar(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,bool,float,bool,float,bool)" (__imp_?registerCvar@CVarManagerWrapper@@QAE?AVCVarWrapper@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00_N1M1M1@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CVarManagerWrapper::registerNotifier(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::function<void __cdecl(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >)>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,unsigned char)" (__imp_?registerNotifier@CVarManagerWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z@3@0E@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __thiscall GameWrapper::GetSteamID(void)" (__imp_?GetSteamID@GameWrapper@@QAE_KXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::HookEventPost(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)>)" (__imp_?HookEventPost@GameWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@3@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::UnhookEvent(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (__imp_?UnhookEvent@GameWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::HookEvent(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)>)" (__imp_?HookEvent@GameWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@3@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::UnregisterDrawables(void)" (__imp_?UnregisterDrawables@GameWrapper@@QAEXXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::RegisterDrawable(class std::function<void __cdecl(class CanvasWrapper)>)" (__imp_?RegisterDrawable@GameWrapper@@QAEXV?$function@$$A6AXVCanvasWrapper@@@Z@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall GameWrapper::SetTimeout(class std::function<void __cdecl(class GameWrapper *)>,float)" (__imp_?SetTimeout@GameWrapper@@QAEXV?$function@$$A6AXPAVGameWrapper@@@Z@std@@M@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class MMRWrapper __thiscall GameWrapper::GetMMRWrapper(void)" (__imp_?GetMMRWrapper@GameWrapper@@QAE?AVMMRWrapper@@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class ServerWrapper __thiscall GameWrapper::GetOnlineGame(void)" (__imp_?GetOnlineGame@GameWrapper@@QAE?AVServerWrapper@@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall GameWrapper::IsInReplay(void)" (__imp_?IsInReplay@GameWrapper@@QAE_NXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall GameWrapper::IsInFreeplay(void)" (__imp_?IsInFreeplay@GameWrapper@@QAE_NXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall GameWrapper::IsInOnlineGame(void)" (__imp_?IsInOnlineGame@GameWrapper@@QAE_NXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: int __thiscall MMRWrapper::GetCurrentPlaylist(void)" (__imp_?GetCurrentPlaylist@MMRWrapper@@QAEHXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: float __thiscall MMRWrapper::GetPlayerMMR(struct SteamID,int)" (__imp_?GetPlayerMMR@MMRWrapper@@QAEMUSteamID@@H@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall MMRWrapper::~MMRWrapper(void)" (__imp_??1MMRWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall ActorWrapper::IsNull(void)" (__imp_?IsNull@ActorWrapper@@QAE_NXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall GameEventWrapper::IsOnlineMultiplayer(void)" (__imp_?IsOnlineMultiplayer@GameEventWrapper@@QAE_NXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CVarWrapper::bindTo(class std::shared_ptr<int>)" (__imp_?bindTo@CVarWrapper@@QAEXV?$shared_ptr@H@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CVarWrapper::bindTo(class std::shared_ptr<bool>)" (__imp_?bindTo@CVarWrapper@@QAEXV?$shared_ptr@_N@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall CVarWrapper::~CVarWrapper(void)" (__imp_??1CVarWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall ServerWrapper::~ServerWrapper(void)" (__imp_??1ServerWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\BMDiscord.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class TeamWrapper __thiscall ArrayWrapper<class TeamWrapper>::Get(int)" (__imp_?Get@?$ArrayWrapper@VTeamWrapper@@@@QAE?AVTeamWrapper@@H@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: int __thiscall ArrayWrapper<class TeamWrapper>::Count(void)" (__imp_?Count@?$ArrayWrapper@VTeamWrapper@@@@QAEHXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall ArrayWrapper<class TeamWrapper>::~ArrayWrapper<class TeamWrapper>(void)" (__imp_??1?$ArrayWrapper@VTeamWrapper@@@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall CarWrapper::~CarWrapper(void)" (__imp_??1CarWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class CarWrapper __thiscall GameWrapper::GetLocalCar(void)" (__imp_?GetLocalCar@GameWrapper@@QAE?AVCarWrapper@@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: unsigned char __thiscall ActorWrapper::GetTeamNum2(void)" (__imp_?GetTeamNum2@ActorWrapper@@QAEEXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: class ArrayWrapper<class TeamWrapper> __thiscall TeamGameEventWrapper::GetTeams(void)" (__imp_?GetTeams@TeamGameEventWrapper@@QAE?AV?$ArrayWrapper@VTeamWrapper@@@@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: __thiscall TeamWrapper::~TeamWrapper(void)" (__imp_??1TeamWrapper@@QAE@XZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: int __thiscall TeamInfoWrapper::GetScore(void)" (__imp_?GetScore@TeamInfoWrapper@@QAEHXZ)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Match.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall MMRWrapper::IsSynced(struct SteamID,int)" (__imp_?IsSynced@MMRWrapper@@QAE_NUSteamID@@H@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\MMR.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: bool __thiscall MMRWrapper::IsSyncing(struct SteamID)" (__imp_?IsSyncing@MMRWrapper@@QAE_NUSteamID@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\MMR.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CanvasWrapper::DrawString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (__imp_?DrawString@CanvasWrapper@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Renderer.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CanvasWrapper::FillBox(struct Vector2)" (__imp_?FillBox@CanvasWrapper@@QAEXUVector2@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Renderer.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CanvasWrapper::SetColor(char,char,char,char)" (__imp_?SetColor@CanvasWrapper@@QAEXDDDD@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Renderer.obj	1	

- Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: void __thiscall CanvasWrapper::SetPosition(struct Vector2)" (__imp_?SetPosition@CanvasWrapper@@QAEXUVector2@@@Z)	BMDiscord	E:\projects\Visual Studios\BMDiscord\BMDiscord\Renderer.obj	1	

- Error	LNK1120	41 unresolved externals	BMDiscord	E:\projects\Visual Studios\BMDiscord\Release\BMDiscord.dll	1

**Comment by Komak57** [comment]
Solved. The current BakkesMod SDK runs on x64, not x86. Compiling accordingly resolves the external symbol errors.

**Comment by MeineZ** [comment]
Ah yes, sorry for my late response! I hope my project helps you out a little! :)
