### ISSUE TITLE
Update of the session windows

### ISSUE THREAD

**Issue by Noustaa** [MeineZ/BMSessionPlugin#12]
Hi, thank you for this plugin it works great ! 
After the match end it looks like the update of the session is done quickly (if i leave the match after 1 or 2 seconds after the end it got the session window updated correctly with the MMR etc...) but if i do not leave the match and stay there until it finds another game, the session window, won't update before leaving the match back to the main menu or finding and load into another match.

Could you please make the session window to update with MMR etc... as soon as it gets the informations when the match ends ? 

Thank you, i can provide more information if needed.

**Comment by MeineZ** [comment]
Hey! Thanks for letting me know! I believe that I already took that into account, but apparently, it doesn't work correctly?

Some more information would be much appreciated, thanks :)

**Comment by Noustaa** [comment]
Hey, sure i will make a video tonight when i get back home and send it there ! Thanks !

**Comment by Noustaa** [comment]
Here is the video, so here i have waited until it finds a new match and you can see the session window is not updated until the new match start, but if i leave to main menu it is being updated correctly once i land on the main menu.

https://user-images.githubusercontent.com/69060343/109862232-7cf3f700-7c60-11eb-947e-bdaff4645ab9.mp4

**Comment by MeineZ** [comment]
Ah, so it correctly updates the plugin? So, you mean it just happens 'too late'?

There's no much I can do about that, unfortunately. The plugin waits for BakkesMod to give an MMR update. So, if BakkesMod doesn't send the update to the plugin, it won't update (obviously).

**Comment by Noustaa** [comment]
Hi, 

Well at the end of the match your MMR is displayed (like for example 946+35 on the video i sent just before) so i guess it is already available somewhere and it would be possible to get it directly from there ?
I'm just giving an idea, i don't really know if it is possible :)

Thanks !

**Comment by MeineZ** [comment]
Yeah, I know. I understand what you're thinking, but the way that the BakkesMod SDK works is a bit odd in some cases. In this particular case (I'm sure more people experience this, I do too), it indeed looks like that the MMR is updated on the scoreboard and it most likely is. However, BakkesMod either doesn't notify the plugin that there has been an MMR update, or the requested MMR after a match hasn't been updated (yet).

In any way, there is not much to do other than inform BakkesMod devs about this issue, which I'll most likely do sooner or later! I'll keep you up-to-date via this issue if you want.

**Comment by MeineZ** [comment]
I've asked BakkesMod devs about this issue. Updates will follow.

**Comment by MeineZ** [comment]
Nope.. Still a thing :')
