### ISSUE TITLE
MMR doesn't update anymore, stays stuck at 600

### ISSUE THREAD

**Issue by rickmastfan67** [MeineZ/BMSessionPlugin#13]
Just recently updated BakkesMod to v142 (injector: 28), and this plugin now no longer keeps track of your MMR after a match is played.  It was working perfectly fine for me till the RL v1.94 got dropped & BakkesMod was updated to work with it on April 6th.

Now, whenever I try to play a game, after the first match is finished and the MMR status window shows up, all it says is that my MMR is 600, doesn't say that I won or lost either, or how much MMR I gained/lost.

If there's anymore info you need, please LMK and I'll try to supply it!

Here's a screenshot of me on the main menu after a game of Rumble showing the issue:
![20210417224831_1](https://user-images.githubusercontent.com/8424257/115132707-703d1f80-9fd0-11eb-8c32-9e8aa07e6029.jpg)

Oh, and this is on Steam.

**Comment by MeineZ** [comment]
Probably a one time thing.
Closing this issue. If this issue keeps occurring, please create a new issue!
