### ISSUE TITLE
Text too small to read

### ISSUE THREAD

**Issue by Daviid000** [MeineZ/BMSessionPlugin#15]
Title says it all. Is there a way to have custom size for the text? Its a bit too small to see. Either a small, medium, or large option or just a bar to text the text size would be amazing. Let me know if this is something you are willing to do or not.

Thanks for the amazing plugin!

**Comment by MeineZ** [comment]
Great to hear there are still people that enjoy using my plugin! Thanks!

This period during the end of the year is extremely busy, so I'll have to take a look at this at some later moment! Though, I believe it's a doable feature request. Thanks for the proposal. I'll look into it somewhere at the start of January and update this thread by then.

**Comment by MeineZ** [comment]
[e6f7216](https://github.com/MeineZ/BMSessionPlugin/commit/e6f721656416f712fcb8183e3b133e1005c64e64)

**Comment by MeineZ** [comment]
[Release 1.12: Add display scaling](https://github.com/MeineZ/BMSessionPlugin/releases/tag/1.12)
Awaiting BakkesMod approval

**Comment by MeineZ** [comment]
Update is available! I believe it automatically updates when booting RocketLeague with BakkesMod, so you should already see the setting in the plugins settings menu!
