### ISSUE TITLE
[Feature Request] Setting to only show stats out of games

### ISSUE THREAD

**Issue by Al12rs** [MeineZ/BMSessionPlugin#2]
I really like the info this plugin is able to give at a glance but I like many others prefer to have as little distractions as possible during matches. 

So I was hoping an option could be added to hide the stats window while the user is in a match. I don't think having the stats during the game is too useful while it would be nice to have it pop up after the match ended.

**Comment by MeineZ** [comment]
I could make that possible, yeah! I'll add it in the near future.

**Comment by MeineZ** [comment]
The option has been added ([commit](ecfc8b0b2644e021b01b874d792edfe45a2ad3cb))! The plugin will be updated by BakkesMod soon!

If you can't wait, you could try to install the [latest release](https://github.com/MeineZ/BMSessionPlugin/releases/tag/1.6) (1.6). Make sure to read the installation instructions in the README.txt (in the release zip)!

**Comment by MeineZ** [comment]
The update has been approved and is now online. It should be in your BakkesMod already!

**Comment by Al12rs** [comment]
Thank you very much! I will go play with it!
