### ISSUE TITLE
Unknown spelled wrong

### ISSUE THREAD

**Issue by NotYorick** [MeineZ/BMSessionPlugin#3]
https://github.com/MeineZ/BMSessionPlugin/blob/ecfc8b0b2644e021b01b874d792edfe45a2ad3cb/SessionPlugin/Playlist.cpp#L25
https://github.com/MeineZ/BMSessionPlugin/blob/ecfc8b0b2644e021b01b874d792edfe45a2ad3cb/SessionPlugin/Playlist.cpp#L45

**Comment by MeineZ** [comment]
Fixed in [this](https://github.com/MeineZ/BMSessionPlugin/commit/28b537d4537a37170c114df06da938a2a9adf897) commit.
