### ISSUE TITLE
Not working with Epic Games?

### ISSUE THREAD

**Issue by hmkyriacou** [MeineZ/BMSessionPlugin#5]
Hi, Since the BakkesMod Epic Games update I have started using the Sessions Stats plugin but I noticed that the MMR and win/loss data seems to not be being collected correctly when playing on Epic Games. After a win, I receive a loss on the session stats window and the MMR is very different from the amount of MMR I lost/gained.

Thank you for your help and for making this plugin!

**Comment by MeineZ** [comment]
Hmmm, that's odd.. I'll experiment with this information during the weekend. :) Thanks for letting me know! Appreciate it :D

**Comment by hmkyriacou** [comment]
![image](https://user-images.githubusercontent.com/30053669/103815882-0658c580-5032-11eb-92c9-70f26620aa8c.png)
I attached a screenshot with some more information... I played 4 games of rumble won 3 and lost 1. The screenshot shows my current MMR, and the SessionStats plugin results.

**Comment by MeineZ** [comment]
Quick, question.. Is this (still) a consistent issue or does it only happen every once in a while?

**Comment by hmkyriacou** [comment]
It looks like it is pretty consistent for me. It may be only the first game that messes up sometimes though, and then the MMR net change is completely off from then out.

**Comment by MeineZ** [comment]
Sorry for taking so long, but I'm going to refactor the method of showing these MMR stats this week(end). This will most likely fix a lot of issues (like this one).

I'll let you know when I've finalized the implementation of that! I'll close this issue and make a new one, watch out for any update in there. If there are still any issues after that update, please let me know again!

[Referenced issue](https://github.com/MeineZ/BMSessionPlugin/issues/9)
