### ISSUE TITLE
Is it possible to include MMR change of all players in CSV instead of just one?

### ISSUE THREAD

**Issue by jacksonmeyn** [MeineZ/BMSessionPlugin#7]
CSV format is currently (e.g. in doubles):

pluginUserMMR, teammateMMR, opponent1MMR, opponent2MMR, pluginUserMMRchange

Could it please be:

pluginUserMMR, teammateMMR, opponent1MMR, opponent2MMR, pluginUserMMRchange, teammateMMRchange, opponent1MMRchange, opponent2MMRchange

No problem if not. I'm currently working with a mathematician to help me create a proposal to Psyonix to improve their ranking system and was recording my MMR data manually until I found your plugin. It's already saving me so much time but if there's any way to include the above columns in the CSV that would be absolutely amazing!

Thanks for a great plugin!

**Comment by MeineZ** [comment]
Amazing to hear that my plugin is being used for other purposes!

What you propose sounds fair, but often there's simply no way to collect the opponent's MMR (e.g. when you leave a match (too) early). That's the main reason why I didn't bother to add the other MMR. There was a second reason, but I can't remember, honestly.

It's quite a change to add that I think, but I may be able to take a look at it soon, I'm quite busy though.

**Comment by MeineZ** [comment]
I may be able to add a setting, that outputs the opponent's MMR change, with a warning that it might produce undefined behaviour; Meaning that the opponents may not have the correct MMR change (probably either 0 or the correct amount).

It might be done fairly quickly, I'll keep you up-to-date! Once it's done, you can always download the release from this GitHub repo to speed up your plugin update locally :)

**Comment by jacksonmeyn** [comment]
Thanks so much. If there's anything I can do to help, please let me know :)

**Comment by MeineZ** [comment]
Okay, so I've tried to add this feature the way I suggested, but the data I get is very inconsistent (far more inconsistent than getting your own MMR). It even seems like it just gives me random data as it can't be the case that my teammate only got 2 MMR points and I got 9 (see first data row) and sometimes the MMR gain is just the player's MMR:

![MMR data](https://user-images.githubusercontent.com/18393968/104565086-09643f00-564c-11eb-8c37-388980c6df95.png)

I'm not really sure if I can fix this, but I'll see what I can do when I have some time again. For now, I could upload it just for the sake that it's there and you could try it out yourself? Just let me know what you prefer.

**Comment by jacksonmeyn** [comment]
Thankyou I've used it for a few days and it is still helpful even if not every data point is recorded. I posted in the bakkesmod subreddit asking how MMR is displayed in the post game screen, and they told me that code is closed source but may be willing to help out with advice. I'll let you know how that goes but for now am happy to close this issue!

**Comment by MeineZ** [comment]
I have been working on a better solution, but it's still in a testing phase right now, as it doesn't output everything as desired yet, I'll push it as soon I get more time to fix it.

It is indeed closed source, unfortunately. Can't wait to hear from you! If you're okay with keeping in contact, you can do so via Discord : Meine#8883
