### ISSUE TITLE
When other people forfeit/quit, win/lose counter increments before games really ends

### ISSUE THREAD

**Issue by DrFrankinStein** [MeineZ/BMSessionPlugin#8]
As title says.

When a teammates forfeit/quit, the lose counter is increased before the game really ends.
When the other team forfeits/quits, the win counter is increased before the game really ends.
After the games ends the counter is then again increased.
It's look like we lost 2 games or win 2 games when only one game was played.
MMR is not affected but streak is.

Running Rocket league and BakkesMod on steam in Windows.

I think the issue is with other player MMR been updated right when they quit.

**Comment by MeineZ** [comment]
Sorry for taking so long, but I'm going to refactor the method of showing these MMR stats this week(end). This will most likely fix a lot of issues (like this one).

I'll let you know when I've finalized the implementation of that! I'll close this issue and make a new one, watch out for any update in there. If there are still any issues after that update, please let me know again!

[Referenced issue](https://github.com/MeineZ/BMSessionPlugin/issues/9)
